"""added socials to user model

Revision ID: 00324e6e80f6
Revises: 996ac76fe336
Create Date: 2023-01-10 22:14:54.172841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00324e6e80f6'
down_revision = '996ac76fe336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('social_twitter', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('social_linkedin', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('social_github', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('social_facebook', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'social_facebook')
    op.drop_column('users', 'social_github')
    op.drop_column('users', 'social_linkedin')
    op.drop_column('users', 'social_twitter')
    # ### end Alembic commands ###
