"""changed varchar to Text for settings-general->googletag

Revision ID: 9910667cb72f
Revises: af5c043662ce
Create Date: 2023-08-20 00:55:37.191271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9910667cb72f"
down_revision = "af5c043662ce"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("settings", schema=None) as batch_op:
        batch_op.alter_column(
            "value",
            existing_type=sa.VARCHAR(length=100),
            type_=sa.Text(),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("settings", schema=None) as batch_op:
        batch_op.alter_column(
            "value",
            existing_type=sa.Text(),
            type_=sa.VARCHAR(length=100),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
