"""SEO Meta Fields

Revision ID: af5c043662ce
Revises: 00324e6e80f6
Create Date: 2023-08-15 22:55:10.691847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af5c043662ce'
down_revision = '00324e6e80f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meta_title', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('meta_description', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('meta_description')
        batch_op.drop_column('meta_title')

    # ### end Alembic commands ###
